export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'
export const SET_INGREDIENT = 'SET_INGREDIENT'
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS'
// export const SEND_ORDER = 'SEND_ORDER'

export const SEND_ORDER_START = 'SEND_ORDER_START'
export const SEND_ORDER_SUCCESS = 'SEND_ORDER_SUCCESS'
export const SEND_ORDER_FAILED = 'SEND_ORDER_FAILED'

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START'
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS'
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED'

export const INIT_PURCHASE = 'INIT_PURCHASE'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILED = 'AUTH_FAILED'

export const LOGOUT = 'LOGOUT'

export const SET_ROUTE_TO_REDIRECT = 'SET_ROUTE_TO_REDIRECT'

